<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-09-06T00:31:00 IST" name="Default suite" finished-at="2022-09-06T00:32:27 IST" duration-ms="86607">
    <groups>
    </groups>
    <test started-at="2022-09-06T00:31:00 IST" name="Default test" finished-at="2022-09-06T00:32:27 IST" duration-ms="86607">
      <class name="webAutomation.webAutomation.Row">
        <test-method is-config="true" signature="startReport()[pri:0, instance:webAutomation.webAutomation.Row@3aee3976]" started-at="2022-09-06T00:31:00 IST" name="startReport" finished-at="2022-09-06T00:31:01 IST" duration-ms="328" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startReport -->
        <test-method signature="FindValueinTable()[pri:0, instance:webAutomation.webAutomation.Row@3aee3976]" started-at="2022-09-06T00:31:01 IST" name="FindValueinTable" finished-at="2022-09-06T00:31:01 IST" duration-ms="51" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FindValueinTable -->
        <test-method is-config="true" signature="screenShot(org.testng.ITestResult)[pri:0, instance:webAutomation.webAutomation.Row@3aee3976]" started-at="2022-09-06T00:31:01 IST" name="screenShot" finished-at="2022-09-06T00:31:01 IST" duration-ms="2" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=FindValueinTable status=SUCCESS method=Row.FindValueinTable()[pri:0, instance:webAutomation.webAutomation.Row@3aee3976] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenShot -->
        <test-method signature="print()[pri:0, instance:webAutomation.webAutomation.Row@3aee3976]" started-at="2022-09-06T00:31:01 IST" name="print" finished-at="2022-09-06T00:32:25 IST" duration-ms="84562" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<3> but was:<2>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<3> but was:<2>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:743)
at org.junit.Assert.assertEquals(Assert.java:118)
at org.junit.Assert.assertEquals(Assert.java:555)
at org.junit.Assert.assertEquals(Assert.java:542)
at webAutomation.webAutomation.Row.print(Row.java:49)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- print -->
        <test-method is-config="true" signature="screenShot(org.testng.ITestResult)[pri:0, instance:webAutomation.webAutomation.Row@3aee3976]" started-at="2022-09-06T00:32:25 IST" name="screenShot" finished-at="2022-09-06T00:32:26 IST" duration-ms="918" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=print status=FAILURE method=Row.print()[pri:0, instance:webAutomation.webAutomation.Row@3aee3976] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- screenShot -->
        <test-method is-config="true" signature="quite()[pri:0, instance:webAutomation.webAutomation.Row@3aee3976]" started-at="2022-09-06T00:32:26 IST" name="quite" finished-at="2022-09-06T00:32:27 IST" duration-ms="651" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quite -->
      </class> <!-- webAutomation.webAutomation.Row -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
